### ISSUE TITLE
sqlite3: Cannot Load such file

### ISSUE THREAD

**Issue by vinsilsim** [dphuang2/PoGoBag#20]
Please anyone can help me?

http://prntscr.com/c3guas

How to solve?

**Comment by JacobCohenIsrael** [comment]
I solved this part but I have another issue

In my `C:\Ruby23-x64\lib\ruby\gems\2.3.0\specifications`
I changed a file named `sqlite3-1.3.11-x64-mingw32.gemspec`
It has a line where it defined as follows: `  s.require_paths = ["lib"]`
So I have changed it to `  s.require_paths = ["lib/sqlite3_native"]`

But now I am stuck in

`Could not load 'active_record/connection_adapters/sqlite3_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.`

**Comment by vinsilsim** [comment]
@JacobCohenIsrael same here!

**Comment by Badcholo** [comment]
I am also stuck at the same thing. It's an exact issue.

**Comment by haitianboy420** [comment]
i am also stuck here

**Comment by animekub** [comment]
I am also stuck at this "rake db:setup" step

**Comment by Badcholo** [comment]
Can i use a WAMP Server to run this?

**Comment by evilhawk00** [comment]
Problem already solved. Follow my directions in issue#1 should solve the problem
https://github.com/dphuang2/PoGoBag/issues/1

**Comment by JacobCohenIsrael** [comment]
This solutions was brought by @evilhawk00 

# The way to solve sqlite_native load problem(Windows Platform):

Before this, make sure you've done the setup of Ruby DevKit.
OKAY,Let's start!
*you should have installed sqlite3 previously after you run gem install bundler , remove sqlite3, run gem uninstall sqlite3 first

1.Go to https://www.sqlite.org/download.html and download the following two files:
source code: sqlite-amalgamation-3140000.zip
Precompiled Binaries for Windows(x86 or x64): sqlite-dll-win32-x86-3140000.zip or sqlite-dll-win64-x64-3140000.zip

2.Let's extract the source code to C:\sqlite-amalgamation-3140000 , make sure this directory contains 4 files (shell.c, sqlite3.c, sqlite3.h, sqlite3ext.h)
3.Let's extract Precompiled Binaries to Ruby's Bin folder, In my case is C:\Ruby23-x64\bin, get the two files from the zip archive and place it into Ruby's Bin folder.
4. Now install sqlite3, with the following command:
With Windows CMD:
gem install sqlite3 --platform=ruby -- --with-sqlite3-include="C:\sqlite-amalgamation-3140000" --with-sqlite3-lib="C:\Ruby23-x64\bin"
OR With Mingw32 Terminal:
gem install sqlite3 --platform=ruby -- --with-sqlite3-include=/C/sqlite-amalgamation-3140000/sqlite-amalgamation-3140000 --with-sqlite3-lib=/c/Ruby23-x64/bin

5.Now run the database setup again, you should not see any error
rake db:setup

**Comment by haitianboy420** [comment]
Thank you JacobCohenIsrael
i can confirm that your steps worked for me

**Comment by TrixuEdits** [comment]
So I did what JacobCohenIsrael said, but now I get this error:

c:\PoGoBag>rake db:setup
rake aborted!
LoadError: cannot load such file -- sqlite3/sqlite3_native
c:/PoGoBag/config/application.rb:7:in `<top (required)>'
c:/PoGoBag/Rakefile:4:in `require_relative'
c:/PoGoBag/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- sqlite3/2.3/sqlite3_native
c:/PoGoBag/config/application.rb:7:in `<top (required)>'
c:/PoGoBag/Rakefile:4:in `require_relative'
c:/PoGoBag/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Anyone know what this means? :(

**Comment by haitianboy420** [comment]
You must not have followed step by step because rake can't find sqlite

**Comment by TrixuEdits** [comment]
> You must not have followed step by step because rake can't find sqlite

Yeah I forgot to uninstall the gem before installing it that way. But I fixed it and it is working now :)

**Comment by Darkkaiba** [comment]
Looks like yesterday sqlite3-amalgamation was updated to 3140100, tried using this but could get it to work...
> 

D:\PKM>rake db:setup
Could not find sqlite3-1.3.11-x86-mingw32 in any of the sources
Run `bundle install` to install missing gems.

D:\PKM>gem install sqlite3 --platform=ruby -- --with-sqlite3-include=/d/sqlite-a
malgamation-3140100 --with-sqlite3-lib=/d/Ruby23-x64/bin
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-sqlite3-include=/d/sqlite-amalgamation-
3140100 --with-sqlite3-lib=/d/Ruby23-x64/bin'
This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: D:/Ruby23/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/ext/sql
ite3
D:/Ruby23/bin/ruby.exe -r ./siteconf20160812-10332-nj0brb.rb extconf.rb --with-s
qlite3-include=/d/sqlite-amalgamation-3140100 --with-sqlite3-lib=/d/Ruby23-x64/b
in
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Ruby23/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
 be found here:

  D:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.3.11/mkmf
.log

extconf failed, exit code 1

Gem files will remain installed in D:/Ruby23/lib/ruby/gems/2.3.0/gems/sqlite3-1.
3.11 for inspection.
Results logged to D:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sql
ite3-1.3.11/gem_make.out

D:\PKM>rake db:setup
Could not find sqlite3-1.3.11-x86-mingw32 in any of the sources
Run `bundle install` to install missing gems.

<

**Comment by evilhawk00** [comment]
@Darkkaiba 
Try to get the old version of it........I don't know if the error is related with the new version

Anyway, I'm making an auto installer which can setup everything for pogobag, it's still WIP,should release first version in 3-5days(my holiday) ,hope it will work for you soon

**Comment by TheWhoDoctor** [comment]
I'm having the same error that Darkkaiba is - except I'm on 3140200... please help!

**Comment by evilhawk00** [comment]
@TheWhoDoctor 
I've made an auto installer can fix all your problem in one click, however I did not get the answer from the project owner if I can publish this redistrubition

If you want it , go to this issue, write down your email, I'll send the one click program to you
https://github.com/dphuang2/PoGoBag/issues/77#issuecomment-248980921
