### ISSUE TITLE
Receiving NoMethodError (undefined method `upcase' for nil:NilClass) when trying to use google api login local

### ISSUE THREAD

**Issue by valmedia** [dphuang2/PoGoBag#24]
`F, [2016-08-09T16:21:06.060061 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] NoMethodError (undefined method `upcase' for nil:NilClass):
F, [2016-08-09T16:21:06.060112 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1]   
F, [2016-08-09T16:21:06.060146 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] app/helpers/sessions_helper.rb:224:in `get_call'
F, [2016-08-09T16:21:06.060197 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] app/helpers/sessions_helper.rb:126:in `get_player_info'
F, [2016-08-09T16:21:06.060237 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] app/helpers/sessions_helper.rb:164:in `setup_client_user_pair'
F, [2016-08-09T16:21:06.060263 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] app/helpers/sessions_helper.rb:156:in `setup_user'
F, [2016-08-09T16:21:06.060293 #20511] FATAL -- : [682af70f-08fa-4184-b16c-533016d350b1] app/controllers/sessions_controller.rb:10:in `create'`

`/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/poke-api-0f56647618ab/lib/poke-api/client.rb:23:in `login'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/poke-api-0f56647618ab/lib/poke-api/client.rb:98:in `check_expiry'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/poke-api-0f56647618ab/lib/poke-api/client.rb:42:in `call'
app/helpers/sessions_helper.rb:224:in `get_call'
app/helpers/sessions_helper.rb:126:in `get_player_info'`

**Comment by nabeelamjad** [comment]
Oops, this might actually be related to ``poke-api``, I may have inadvertently introduced an old bug that was fixed. For now you can avoid it by not calling the provider with all caps.

**Comment by valmedia** [comment]
Weird seems to be quite buggy for local installation. Now gets user/password invalid and calling login_error_ptc.
